apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: hygieia-jenkins-build-collector
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: hygieia-jenkins-build-collector
    name: hygieia-jenkins-build-collector
  spec:
    serviceName: jenkins
    replicas: 1
    selector:
      deploymentconfig: hygieia-jenkins-build-collector
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hygieia-jenkins-build-collector
          deploymentconfig: hygieia-jenkins-build-collector
      spec:
        serviceAccountName: jenkins
        containers:
        - env:
          - name: DBNAME
            valueFrom:
              secretKeyRef:
                key: database-name
                name: mongodb
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mongodb
          - name: DBHOST
            value: mongodb.${NAMESPACE}.svc
          - name: JENKINS_CRON
            value: '5 * * * * *'
          - name: JENKINS_SERVERS
            value: https://admin:password@jenkins-${NAMESPACE}.${OPENSHIFT_DEFAULT_SUBDOMAIN}
          - name: DBPORT
            value: "27017"
          - name: MONGO_PORT
            value: "27017"
          - name: DBUSERNAME
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mongodb
          - name: LOGGING_LEVEL_ROOT
            value: INFO
          - name: JENKINS_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: jenkins-token-qc67q
                key: token
          - name: JENKINS_CLIENT_ID
            value: system:serviceaccount:${NAMESPACE}:jenkins
          image: hygieia-jenkins-build-collector:latest
          imagePullPolicy: Always
          name: hygieia-jenkins-build-collector
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - hygieia-jenkins-build-collector
        from:
          kind: ImageStreamTag
          name: hygieia-jenkins-build-collector:latest
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange
parameters:
- name: NAMESPACE
- name: OPENSHIFT_DEFAULT_SUBDOMAIN
