# https://github.com/jenkinsci/job-dsl-plugin
controller:
  additionalPlugins:
    - job-dsl:1.93
  ingress:
    enabled: true
persistence:
  enabled: false
rbac:
  readSecrets: true
serviceAccount:
  create: true
