---
namespace: liberty-demo

openshift_cluster_content:
- object: Environment Setup
  content:
  - name: Create Projects
    template: "https://raw.githubusercontent.com/redhat-cop/openshift-templates/v1.4.5/project-requests/create-project.yml"
    action: create
    params_from_vars:
      NAMESPACE: "{{ namespace }}"
      NAMESPACE_DISPLAY_NAME: "{{ namespace }}"
    tags:
      - project
- object: builds
  content:
  - name: "Build application"
    namespace: liberty-demo
    template: "{{ inventory_dir }}/../.openshift/templates/build.yml"
    params: "{{ inventory_dir }}/../.openshift/params/build-dev"
- object: deployments
  content:
  - name: "deploy dev environment"
    namespace: liberty-demo
    template: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    params: "{{ inventory_dir }}/../.openshift/params/deployment-dev"
