namespace: docker-build
app_name: dockerbuild

build:
  NAME: "{{ app_name }}"
  SOURCE_REPOSITORY_URL: https://github.com/pcarney8/containers-quickstarts.git
  SOURCE_REPOSITORY_REF: add-generic-dockerbuild
  SOURCE_CONTEXT_DIR: build-docker-generic

openshift_cluster_content:
- object: Environment Setup
  content:
  - name: Create Projects
    template: "https://raw.githubusercontent.com/redhat-cop/openshift-templates/v1.4.5/project-requests/create-project.yml"
    action: create
    params_from_vars:
      NAMESPACE: "{{ namespace }}"
      NAMESPACE_DISPLAY_NAME: "{{ namespace }}"
    tags:
      - project
- object: Builds
  content:
  - name: "{{ app_name }}"
    template: "{{ inventory_dir }}/../.openshift/templates/docker-build-template.yml"
    params_from_vars: "{{ build }}"
    namespace: "{{ namespace }}"
    tags:
      - build
