sonatype-nexus:
  nexus:
    imageName: sonatype/nexus3
    imageTag: 3.19.1
    service:
      type: ClusterIP
      podAnnotations: {}
    securityContextEnabled: false

  route:
    enabled: true
    name: nexus
    portName: nexus-service
    path: '""' 

  nexusProxy:
    enabled: false

  persistence:
    storageSize: 5Gi

  serviceAccount:
    name: nexus
    annotations: {}

  additionalConfigMaps:
    - name: jboss-public
      labels:
        nexus-type: repository
      data:
        recipe: 'MavenProxy'
        remoteUrl: 'https://repository.jboss.org/nexus/content/groups/public/'
        blobStoreName: 'default'
        strictContentTypeValidation: 'true'
        versionPolicy: 'RELEASE'
        layoutPolicy: 'STRICT'
    - name: redhat-ga
      labels:
        nexus-type: repository
      data:
        recipe: 'MavenProxy'
        remoteUrl: 'https://maven.repository.redhat.com/ga/'
        blobStoreName: 'default'
        strictContentTypeValidation: 'true'
        versionPolicy: 'RELEASE'
        layoutPolicy: 'STRICT'
    - name: redhat-earlyaccess
      labels:
        nexus-type: repository
      data:
        recipe: 'MavenProxy'
        remoteUrl: 'https://maven.repository.redhat.com/earlyaccess/all/'
        blobStoreName: 'default'
        strictContentTypeValidation: 'true'
        versionPolicy: 'RELEASE'
        layoutPolicy: 'STRICT'
    - name: redhat-public
      labels:
        nexus-type: repository
      data:
        recipe: 'MavenGroup'
        members: jboss-public,redhat-ga,redhat-earlyaccess
        blobStoreName: 'default'
    - name: maven-public
      labels:
        nexus-type: repository
      data:
        recipe: 'MavenGroup'
        members: maven-releases,maven-snapshots,maven-central,redhat-public

  deployment:
    annotations: {}
    initContainers:
      - name: k8s-plugin-puller
        image: curlimages/curl:latest
        imagePullPolicy: Always
        command: ['sh','-c']
        args: ['curl -L -o /k8s-plugin/nexus-openshift-plugin.jar https://github.com/sonatype-nexus-community/nexus-kubernetes-openshift/releases/download/v0.2.8/nexus-openshift-plugin-0.2.8.jar']
        volumeMounts:
          - name: k8s-plugin
            mountPath: /k8s-plugin
    additionalVolumes:
      - name: k8s-plugin
        emptyDir: {}
    additionalVolumeMounts:
      - mountPath: /opt/sonatype/nexus/deploy/nexus-openshift-plugin.jar
        name: k8s-plugin
        subPath: nexus-openshift-plugin.jar

  service:
    enabled: true
    name: nexus-service
    labels: {}
    annotations: {}
    portName: nexus-service
    port: 8081
    targetPort: 8081
    ports: []
