---
name: jenkins-agent-helm-pr
on:
  pull_request:
    paths:
      - jenkins-agents/jenkins-agent-helm/**
      - .github/workflows/jenkins-agent-helm-pr.yaml
jobs:
  build:
    env:
      context: jenkins-agents/jenkins-agent-helm
      image_name: jenkins-agent-helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Dockerfile
          image: ${{ env.image_name }}
          oci: true
          tags: "latest"