name: tekton-task-images-helm-pr
on:
  pull_request:
    paths:
      - tekton-task-images/helm/**
      - .github/workflows/tekton-task-images-helm-pr.yaml
jobs:
  build:
    env:
      context: tekton-task-images/helm
      image_name: helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert VERSION to version.json
        run: |
          version=$(cat ${{ env.context }}/VERSION | cut -d"=" -f2)
          jq -c --null-input --arg version "v$version" '{ "version": $version }' > ${{ env.context }}/version.json

      - name: Check and verify version.json
        id: check_version
        uses: redhat-cop/github-actions/get-image-version@master
        with:
          IMAGE_CONTEXT_DIR: ${{ env.context }}

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Dockerfile
          image: ${{ env.image_name }}
          oci: true
          tags: ${{ steps.check_version.outputs.IMAGE_TAGS }}
      - name: Test image contains the version of the binary
        run: |
          echo "Running: podman run ${image_name}:${{ steps.check_version.outputs.VERSION }} helm version"
          podman run ${image_name}:${{ steps.check_version.outputs.VERSION }} helm version | grep ${{ steps.check_version.outputs.VERSION }}
