name: tekton-task-images-helm-pr
on:
  pull_request:
    paths:
      - tekton-task-images/helm/**
      - .github/workflows/tekton-task-images-helm-pr.yaml

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    env:
      context: tekton-task-images/helm
      image_name: helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Convert VERSION to version.json
        run: |
          version=$(sed -n '2p' ${{ env.context }}/VERSION | cut -d"=" -f2)
          jq -c --null-input --arg version "$version" '{ "version": $version }' > ${{ env.context }}/version.json

      - name: Check and verify version.json
        id: check_version
        uses: redhat-cop/github-actions/get-image-version@11f2ce27643eb7c76ac3623cb99d9b08be30d762 # v4
        with:
          IMAGE_CONTEXT_DIR: ${{ env.context }}

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ${{ env.context }}/Dockerfile
          ignore: DL3041,SC1091

      - name: Build image
        uses: redhat-actions/buildah-build@b4dc19b4ba891854660ab1f88a097d45aa158f76 # v2
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Dockerfile
          image: ${{ env.image_name }}
          oci: true
          tags: ${{ steps.check_version.outputs.IMAGE_TAGS }}

      - name: Test image contains the version of the binary
        run: |
          echo "Running: podman run ${image_name}:${{ steps.check_version.outputs.VERSION }} helm version"
          podman run ${image_name}:${{ steps.check_version.outputs.VERSION }} helm version | grep ${{ steps.check_version.outputs.VERSION }}
