name: tekton-task-images-helm-pr
on:
  pull_request:
    paths:
      - tekton-task-images/helm/VERSION
jobs:
  build:
    env:
      context: tekton-task-images/helm
      image_name: helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
           # exposes variable HELM_VERSION
          source ${context}/VERSION
          echo ${HELM_VERSION}
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          path: ${{ env.context }}
          push: false
          repository: ${{ env.image_name }}
          tags: ${{ steps.check_version.outputs.IMAGE_TAGS }}
      - name: Test image contains the version of the binary
        run: |
          echo "Running: docker run ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} helm version"
          docker run ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} helm version | grep ${{ steps.check_version.outputs.IMAGE_TAGS }}